name: Documentation

on:
  pull_request:
    types: [closed]
    branches:
      - "main"

jobs:
  generate-docs:
    name: Générer la documentation avec Maven
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Generate Javadoc with Maven
        run: mvn -B javadoc:javadoc 

  deploy-docs:
    name: Déployer la documentation sur GitHub Pages
    runs-on: ubuntu-latest
    needs: generate-docs
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy Javadoc to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} 
          publish_dir: ./target/reports/javadoc